# Generated by Django 5.2.8 on 2025-11-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='job_role',
            field=models.CharField(choices=[('employer', 'Employer'), ('employee', 'Employee'), ('company', 'Company')], max_length=20),
        ),
    ]
