# Generated by Django 5.2.8 on 2025-12-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_postings', '0002_alter_jobapplication_options_and_more'),
    ]

    operations = [
    ]
