# Generated by Django 5.2.8 on 2025-12-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_postings', '0003_auto_20251207_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='applicant_email',
            field=models.EmailField(default='noemail@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applicant_phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(default='No cover letter provided'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(default='resumes/default_resume.pdf', upload_to='resumes/%Y/%m/'),
        ),
    ]
