@echo off
echo Starting Django Backend Server...
echo.
echo Activating virtual environment...
call venv\Scripts\activate
echo.
echo Installing/updating dependencies...
pip install -r requirements.txt
echo.
echo Running migrations...
python manage.py migrate
echo.
echo Starting Django development server...
python manage.py runserver
pause