# Generated by Django 5.2.8 on 2025-11-20 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
    ]
