# Generated by Django 5.2.8 on 2025-11-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_remove_profile_created_at_remove_profile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.TextField(blank=True, help_text='Work experience', null=True),
        ),
    ]
