# Generated by Django 5.2.8 on 2025-12-03 13:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('profile_app', '0005_companyprofile_employeeprofile_employerprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('post_type', models.CharField(choices=[('text', 'Text Post'), ('image', 'Image Post'), ('achievement', 'Achievement'), ('job_update', 'Job Update')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/')),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'profile_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'post_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'post_likes',
            },
        ),
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='experience',
            new_name='experience_details',
        ),
        migrations.RenameField(
            model_name='employerprofile',
            old_name='education',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='benefits_offered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_type',
            field=models.CharField(blank=True, choices=[('startup', 'Startup'), ('small', 'Small Business'), ('medium', 'Medium Enterprise'), ('large', 'Large Enterprise'), ('nonprofit', 'Non-Profit'), ('government', 'Government')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_values',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_covers/'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='headquarters_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='is_verified_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='verification_documents',
            field=models.FileField(blank=True, null=True, upload_to='company_verification/'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='work_culture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='expected_salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='expected_salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='notice_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='open_to_remote',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='preferred_job_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='is_verified_employer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='specialization_areas',
            field=models.TextField(blank=True, help_text='Areas of expertise for hiring', null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='employer_verification/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='years_of_hiring_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1000+', '1000+ employees')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='industry',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='employee_resumes/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['company_name', 'industry'], name='company_pro_company_77ee2f_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['is_verified_company'], name='company_pro_is_veri_635582_idx'),
        ),
        migrations.AlterModelTable(
            name='companyprofile',
            table='company_profiles',
        ),
        migrations.AlterModelTable(
            name='employeeprofile',
            table='employee_profiles',
        ),
        migrations.AlterModelTable(
            name='employerprofile',
            table='employer_profiles',
        ),
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='profile_app.post'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='profile_app.post'),
        ),
        migrations.AddField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['content_type', 'object_id'], name='profile_pos_content_bce023_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='profile_pos_created_401e51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('post', 'user')},
        ),
    ]
